import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Project: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Project page</h1>
        <Link href="/">
          <a>Link back home</a>
        </Link>
      </main>
    </div>
  );
};

export default Project;
