import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../../styles/Home.module.css';

const Projects: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Projects page</h1>
        <Link href="/">
          <a>Link back home</a>
        </Link>
        <Link href="/projects/123">
          <a>Specific project</a>
        </Link>
      </main>
    </div>
  );
};

export default Projects;
